### ISSUE TITLE
Page completely broken due to new box styling

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-older-users#17]
<img width="416" alt="trash" src="https://user-images.githubusercontent.com/6991814/45838527-8464f700-bcd7-11e8-8767-be2f4278008d.png">

**Comment by yatil** [comment]
This is due to broken code. I have to investigate.
<img width="1063" alt="screen shot 2018-09-20 at 8 19 08 pm" src="https://user-images.githubusercontent.com/58862/45838647-88fad100-bd12-11e8-8547-e2fa1f8b5b99.png">

**Comment by shawna-slh** [comment]
ah, right, just now seeing that part :-(

I'm wanting to point a reporter to this today . . .

**Comment by yatil** [comment]
@slhenry The page is now working again. Looks like the “strip_html” command for using the title as aria-labels does not do what it should… *sigh* I reopened w3c/wai-website#26 to keep track of the issue.
