### ISSUE TITLE
Language standard

### ISSUE THREAD

**Issue by a11ycob** [w3c/wai-older-users#2]
Going through this resource I see that "ageing" is spelled with an "E", which is fine if we are using the UK convention. However, if you see the word color it is spelled using the US convention instead of "colour". I recommend that we stick with one convention or another.

Speaking of which, do we have an official language standard that we follow?

**Comment by yatil** [comment]
@a11ycob Our [style guide](https://www.w3.org/WAI/EO/wiki/Style) explicitly says:

> Spelling: We generally use US spellings. One exception: "ageing". ([ageing background](https://www.w3.org/WAI/EO/wiki/Style#ageing_background))

I stumbled over this as well :-)

**Comment by a11ycob** [comment]
Ah, good to know. Late to the party (as usual)

Thanks, Eric!
