### ISSUE TITLE
[!!] [Lit Review] vision decline missing

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-older-users#7]
https://w3c.github.io/wai-older-users/older-users/literature/#summary-of-impact-and-prevalence

has hearing, physical, cognitive. is missing visual.

I'm guessing @nitedog included it, and we've lost it in the editing. Vicki, Shadi - can you find it?

**Comment by nitedog** [comment]
Here it is (big thanks to public archives):
 - https://lists.w3.org/Archives/Public/public-eo-archive/2017OctDec/att-0020/Presentation.htm

**Comment by shawna-slh** [comment]
incorporated (didn't copy edit much)
